// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prlbaxfdkdrwcnffhkfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBybGJheGZka2Ryd2NuZmZoa2Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNTU3NTksImV4cCI6MjA1MzgzMTc1OX0.ILWgZDOCqQOoY6oys3H1GvnomcmlK1A8qDp3HrnElmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);